services:
  - type: web
    name: my-airflow-project
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        value: postgresql+psycopg2://bda_2dog_user:CfjVbrAnbPIFtbxHeN1z6tAzPbq4yJal@dpg-ctpgf2t2ng1s73drs8hg-a.oregon-postgres.render.com:5432/bda_2dog
      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor
      - key: AIRFLOW__CORE__DAGS_FOLDER
        value: /opt/airflow/dags
      - key: AIRFLOW__CORE__LOAD_EXAMPLES
        value: "False"
      - key: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
        value: "8080"
      - key: AIRFLOW__WEBSERVER__WEB_SERVER_HOST
        value: "0.0.0.0"
      - key: AIRFLOW__WEBSERVER__WORKER_TIMEOUT
        value: "600"
      - key: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
        value: "300"
      - key: AIRFLOW__WEBSERVER__WORKERS
        value: "1"
      - key: AIRFLOW__WEBSERVER__AUTH_BACKEND
        value: airflow.www.auth.no_auth
      - key: AIRFLOW__WEBSERVER__AUTHENTICATE
        value: "False"
